### ISSUE TITLE
request to add units

### ISSUE THREAD

**Issue by gioassio89** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#22] opened 2024-04-17 12:05 UTC
Hi,
it is possible to add these units in the integration?
W
Kwh
min
sec
h
%RH
ppm
V

thanks a lot

**Comment by GravySeal** [comment] 2024-04-17 18:38
I just released integration version v0.2.1b1. Could you update and see if the units work for you?

**Comment by gioassio89** [comment] 2024-04-17 21:13
yes, perfectly:
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/3bd02814-ffff-4e6c-85a1-43e33ef4f114)

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/4e1f1dd2-aa51-481a-a241-9593e28d406c)

the only variable that i cannot see in my export is deg (degree angular) the other are all show.
one question: i cannot see energy variabe in the HA enery manager:
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/81e1048c-7e1e-4904-9013-bc2d447087f1)

according to the HA documentation the "state_class" must be "total" or "total_increasing"
the imported point has "state_class" set as measurements:
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/1a759bae-d231-4d07-9251-4b32ab031f5b)
there is any way to  change the state_class?
thanks a lot!

**Comment by Bepacom-Raalte** [comment] 2024-04-18 06:09
I can add the degrees as units for angular. The user can't change the state class. I can make it so the entity becomes state class total if the unit of measurement is one of those.
Please try v0.2.1b2 to see if it works for you.

**Comment by gioassio89** [comment] 2024-04-18 20:55
Hi! works perfectly now!!!
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/bb0e6ada-4d64-4bf3-bd0a-52bc484dafa4)

 Also ° are displayed now!
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/81fb9557-ed57-4139-b2c0-1e2ab76a7723)


Can you change the state_class also for volumetric point  in "total" or "total_increasing"?
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/a5959a66-0edb-455a-be69-307067641c7e)
Thanks a lot!

**Comment by Bepacom-Raalte** [comment] 2024-04-19 06:22
Great to hear, added UnitOfVolume to be state_class total as well. Could you try v0.2.1b3?

**Comment by gioassio89** [comment] 2024-04-20 09:44
Hi Thanks,
i think that is needed to change the device_class in water:
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/db239f1a-ef53-47c5-895f-b88df1f245ad)
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/166951559/4f29b0ec-a0c4-4392-9bf7-738f0aa82f2b)
it is possible for you to assign the device class accordind to bacnet point descriptor? eg if in the point description there is "Water" the device_class will be "Water"?

**Comment by GravySeal** [comment] 2024-04-20 11:41
It would be possible to do based on description, but then the issue is languages. In each language, it'll be something else so it's going to be difficult to make it work right.
I think a better solution would be to use a template sensor with the right device class using the value of the right entity like so:

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/93523925/fc467331-6f1b-466d-976f-ef89fd91c185)

**Comment by gioassio89** [comment] 2024-04-20 20:10
Great Idea! it Works! Thanks a lot!
All of Units that i need work now, should i close this issue?

**Comment by GravySeal** [comment] 2024-04-21 09:47
I'll close this issue for you, glad this solution works for you!

**Closed by GravySeal** 2024-04-21 09:47 UTC
